name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch or any branch you'd like to deploy from
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the Node.js version compatible with your Angular app

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod  # This assumes your Angular build output goes to 'dist/<project-name>'

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: '/'  # Root of the Angular project
          output_location: 'dist'  # Path to the build output folder, replace <project-name> with your Angular app's output folder name
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_RIVER_033858E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
